# Site settings
title: Finally, a blog!
description: > #
url: "http://www.chrisdonnelly.com"
name: "Chris R. Donnelly"

theme: jekyll-theme-cayman

permalink: /:categories/:year/:month/:day/:title/
contenturl: "/blog/content/"

# Social
twitter_username: cdonnellytx
github_username: cdonnellytx
stackoverflow_link: users/17152/chris-r-donnelly
googleplus_id: 112563910740791984026

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
