# Site settings
title: Finally, a blog!
description: > #
url: http://www.chrisdonnelly.com
baseurl: ""
author: Chris R. Donnelly
email: blog@chrisdonnelly.com
lang: en-US
repository: cdonnellytx/cdonnellytx.github.io

# UX
#theme: jekyll-theme-cayman
theme: jekyll-theme-clean-blog
image: "/assets/img/bg/home.jpg"
postImage: "/assets/img/bg/about.jpg"

permalink: /:categories/:year/:month/:day/:title/

# Social
twitter_username: cdonnellytx
github_username: cdonnellytx
facebook_username: cdonnellytx
stackoverflow_link: users/17152/chris-r-donnelly
googleplus_id: 112563910740791984026

# Build settings
exclude:
  - .editorconfig
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
