# Site settings
title: Finally, a blog!
description: Because the Internet doesn't have enough blogs already. #
url: http://www.chrisdonnelly.com
baseurl: ""
author: Chris R. Donnelly
email: blog@chrisdonnelly.com
lang: en-US
repository: cdonnellytx/cdonnellytx.github.io

# UX
# 2018-01-16: This is the theme I'm using, but GitHub Pages won't honor it.
# So I copied in all its resources locally so I don't have to build it every single time I post, like an animal or the Apple Store.
#theme: jekyll-theme-clean-blog
image: "/assets/img/bg/home.jpg"
permalink: /:categories/:year/:month/:day/:title/

# Social
twitter_username: cdonnellytx
github_username: cdonnellytx
facebook_username: cdonnellytx
stackoverflow_link: users/17152/chris-r-donnelly
googleplus_id: 112563910740791984026

# Build settings
exclude:
  - .editorconfig
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - .vscode
